### ISSUE TITLE
Add additional column for 'type'

### ISSUE THREAD

**Issue by Burnett2k** [Burnett2k/Programming-Music#16]
Right now, there is a `album/playlist` column which might be kind of confusing. It could be better to just have a type column where the user can then enter from these options `Album`, `Playlist`, `Song`.

This change would require going through and updating the `Type` for each row. This should get done before the lists gets too long!

Steps to complete:
1. Add new Name column as the second column
2. Rename Album/Playlist column to be Type
3. Update the type column for each item to state whether it is a playlist, album, song, etc

Example:

|Artist|Name|Type|Link|
|---|---|---|---|
|STS 9|Moon Socket|Album|[link](https://open.spotify.com/album/3D0Qas7vQzxhtSQh7zHfln?si=D3dJBa4dQVOYjpO3ZaS4uA)|

**Comment by am2367** [comment]
@Burnett2k done

**Comment by Burnett2k** [comment]
Step 3 still needs to be completed if you don't mind helping with that

**Comment by Burnett2k** [comment]
@am2367 nicely done. Closing the issue.
