### ISSUE TITLE
add categories to list

### ISSUE THREAD

**Issue by Burnett2k** [Burnett2k/Programming-Music#9]
It would be great if we had categories so depending on your mood you can look into the different tables. If someone wants to rework the list to have genres, that would be cool

**Comment by apfzvd** [comment]
Hello, I really like this idea! I think we could start with **Relaxing**, **Focus**, **Fun** as major categories for the albums/playlists, what do you think?

**Comment by Fernando0107** [comment]
That sounds awesome! I will try to help!

**Comment by Burnett2k** [comment]
Agreed. I think maybe adding Electronic would be good as well for STS9 in particular.

**Comment by apfzvd** [comment]
Nice! I'll add the **Relaxing**, **Focus**, **Fun** and **Eletronic** categories as soon as I can! 
Do you guys think it's better to add the categories as separated tables or as a column on the list table?

**Comment by Burnett2k** [comment]
I think separate tables would probably be best for now to keep the lists more separate.
